#
# *** DO NOT EDIT THIS FILE ***
# Generated on Mon Oct 10 03:01:09 2016 UTC, by
#   Mesoderm (0.140780)
#   Moose::Object (2.1806)
#

package Peptide::Schema::_mesoderm;
use Moose::Role;
sub schema { shift->result_source->schema->{__mesoderm} }

package Peptide::Schema::_dbic;
use base qw(DBIx::Class::Schema);

package Peptide::Schema::_scaffold;
use Moose::Role;
require Scalar::Util;
requires 'connect_args';

has 'dbic' => (
  is => 'ro',
  isa => 'Peptide::Schema::_dbic',
  lazy => 1,
  default => sub {
    my $self = shift;
    my $dbic = Peptide::Schema::_dbic->connect( $self->connect_args );
    Scalar::Util::weaken($dbic->{__mesoderm} = $self);
    return $dbic;
  },
);

##
## Table: uniprot_yeast
##

has 'uniprot_yeast' => (
  is      => 'ro',
  lazy    => 1,
  isa     => 'Peptide::Schema::ResultSet::UniprotYeast',
  default => sub { shift->dbic->resultset('uniprot_yeast'); },
);

{
  package Peptide::Schema::UniprotYeast;
  use Moose;
  extends 'DBIx::Class';

  __PACKAGE__->load_components(qw/ Core /);

  with qw(
    Peptide::Schema::_mesoderm
    );
  no Moose;

  __PACKAGE__->table('uniprot_yeast');
  __PACKAGE__->add_columns(
    id => {
      data_type => 'INTEGER',
      default_value => 'nextval(\'uniprot_yeast_id_seq\'::regclass)',
      is_nullable => 0,
      size => 0
    },
    peptide => {
      data_type => 'CHARACTER VARYING(1000)',
      default_value => undef,
      is_nullable => 1,
      size => 1004
    },
    bullbreese => {
      data_type => 'REAL',
      default_value => undef,
      is_nullable => 1,
      size => 0
    },
    hodges_prediction => {
      data_type => 'REAL',
      default_value => undef,
      is_nullable => 1,
      size => 0
    },
  );
  { package Peptide::Schema::ResultSet::UniprotYeast;
    use Moose;
    extends 'DBIx::Class::ResultSet';
    with qw(
      Peptide::Schema::_mesoderm
      );
    no Moose;
  }
  __PACKAGE__->set_primary_key('id');
  __PACKAGE__->resultset_class('Peptide::Schema::ResultSet::UniprotYeast');
  Peptide::Schema::_dbic->register_class( uniprot_yeast => __PACKAGE__ );
}


1;
